package edu.lehigh.cse280.backend;

import org.springframework.security.crypto.bcrypt.BCrypt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.net.URI;
import java.net.URISyntaxException;

import java.util.ArrayList;

public class Database {
    /**
     * The connection to the database
     */
    private Connection mConnection;

    /**
     * Some prepared statements
     */
    private PreparedStatement uGmail;
    private PreparedStatement uCreateTable;
    private PreparedStatement uDropTable;
    private PreparedStatement uInsertOne;
    private PreparedStatement uUpdateOne;
    private PreparedStatement uSelectAll;
    private PreparedStatement uSelectOne;
    private PreparedStatement uDeleteOne;
    private PreparedStatement uSelectAllWithQuery;
    private PreparedStatement uCheckAdmin;

    /**
     * The Database constructor is private: we only create Database objects
     * through the getDatabase() method.
     */
    private Database() {

    }

    public void init() {
        try {
            uCreateTable.execute();
            // cCreateTable.execute();
        } catch(Exception e) {
            e.printStackTrace();
            //disconnect();
        }
    }

    /**
     * Connect to the Database
     */
    static Database getDatabase(String db_url) {
        Database db = new Database();;
        try {
            Class.forName("org.postgresql.Driver");
            URI dbUri = new URI(db_url);
            String username = dbUri.getUserInfo().split(":")[0];
            String password = dbUri.getUserInfo().split(":")[1];
            String dbUrl = "jdbc:postgresql://" + dbUri.getHost() + ':' + dbUri.getPort() + dbUri.getPath();
            Connection conn = DriverManager.getConnection(dbUrl, username, password);
            if (conn == null) {
                System.err.println("Error: DriverManager.getConnection() returned a null object");
                return null;
            }
            db.mConnection = conn;
        } catch (SQLException e) {
            System.err.println("Error: DriverManager.getConnection() threw a SQLException");
            e.printStackTrace();
            return null;
        } catch (ClassNotFoundException cnfe) {
            System.out.println("Unable to find postgresql driver");
            return null;
        } catch (URISyntaxException s) {
            System.out.println("URI Syntax Error");
            return null;
        }
        

        // Create prepared statement
        try {
            db.uCreateTable = db.mConnection
                    .prepareStatement("CREATE TABLE tblUser (uid SERIAL PRIMARY KEY, username VARCHAR(50) "
                            + "NOT NULL, email VARCHAR(500) NOT NULL, gender INTEGER, tidiness INTEGER, "
                            + "noise INTEGER, sleep INTEGER, wake INTEGER, pet INTEGER, visitor INTEGER, hobby VARCHAR(500), admin INTEGER NOT NULL)");
            db.uDropTable = db.mConnection.prepareStatement("DROP TABLE tblUser");

            // insert only name and email into uTable, uid is auto generated by the database and the rest are null;
            db.uInsertOne = db.mConnection.prepareStatement("INSERT INTO tblUser VALUES (default, ?, ?, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ?)");
            db.uGmail = db.mConnection.prepareStatement("SELECT * from tblUser WHERE email = ?");
            db.uUpdateOne = db.mConnection
                    .prepareStatement("UPDATE tblUser SET username = ?, gender = ?, tidiness = ?, noise = ?, sleep = ?, wake = ?, pet = ?, "
                            + "visitor = ?, hobby = ? WHERE uid = ?");
            db.uSelectAll = db.mConnection.prepareStatement("SELECT * from tblUser");
            db.uSelectOne = db.mConnection.prepareStatement("SELECT * from tblUser WHERE uid = ?");
            db.uDeleteOne = db.mConnection.prepareStatement("DELETE FROM tblUser WHERE uid = ?");
            db.uSelectAllWithQuery = db.mConnection
                    .prepareStatement("SELECT * from tblUser WHERE gender BETWEEN ? AND ? "
                                                            + "AND tidiness BETWEEN ? AND ? "
                                                            + "AND noise BETWEEN ? AND ? "
                                                            + "AND sleep BETWEEN ? AND ? "
                                                            + "AND wake BETWEEN ? AND ? "
                                                            + "AND pet BETWEEN ? AND ? "
                                                            + "AND visitor BETWEEN ? AND ?");
            db.uCheckAdmin = db.mConnection.prepareStatement("SELECT admin from tblUser WHERE uid = ?");

        } catch (SQLException e) {
            System.err.println("Error creating prepared statement");
            e.printStackTrace();
            db.disconnect();
            return null;
        }
        return db;
    }

    /**
     * Close the current connection to the Database, if one exists.
     * 
     * @return True if the connection was cleanly closed, false otherwise.
     */
    boolean disconnect() {
        if (mConnection == null) {
            System.err.println("Unable to close connection: Connection was null");
            return false;
        }
        try {
            // cDropTable.execute();
            uDropTable.execute();
            mConnection.close();
        } catch (SQLException e) {
            System.err.println("Error: Connection.close() threw a SQLException");
            e.printStackTrace();
            mConnection = null;
            return false;
        }
        mConnection = null;
        return true;
    }

    // check if the user with the param email exist in tbluser
    public DataRowUserProfile matchUsr(String email) {
        DataRowUserProfile res = null;
        try {
            uGmail.setString(1, email);
            ResultSet rs = uGmail.executeQuery();
            if (rs.next())
                res = new DataRowUserProfile(rs.getInt("uid"), rs.getString("username"), rs.getString("email"), rs.getInt("admin"));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return res;
    }

    // insert the user into tbluser
    public int insertRowToUser(String email, int admin) {
        int count = 0;
        try {
            // Use email as default user name
            uInsertOne.setString(1, email.split("@")[0]);
            uInsertOne.setString(2, email);
            uInsertOne.setInt(3, admin);
            count += uInsertOne.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return count;
    }

    // read uid, username, and email of all users in tbluser 
    public ArrayList<DataRowUserProfile> readAll() {
        ArrayList<DataRowUserProfile> res = new ArrayList<DataRowUserProfile>();
        try {
            ResultSet rs = uSelectAll.executeQuery();
            while (rs.next()) {
                //readAll只需要显示uID uName和uEmail，所以用DataRowUserProfile足够了
                res.add(new DataRowUserProfile(rs.getInt("uid"), rs.getString("username"), rs.getString("email")));
            }
            rs.close();
            return res;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    // read uid, username, and email of all users in tbluser with search query
    public ArrayList<DataRowUserProfile> readAll(int values[]) {
        ArrayList<DataRowUserProfile> res = new ArrayList<DataRowUserProfile>();
        try {
            for (int i = 0; i < values.length; i++) {
                uSelectAllWithQuery.setInt(i+1, values[i]);
            }
            ResultSet rs = uSelectAllWithQuery.executeQuery();
            while (rs.next()) {
                res.add(new DataRowUserProfile(rs.getInt("uid"), rs.getString("username"), rs.getString("email")));
            }
            rs.close();
            return res;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    // update user profile in tbluser
    public int updateOne(int uid, String username, int gender, int tidiness, int noise, int sleep, int wake, int pet, int visitor, String hobby) {
        try {
            uUpdateOne.setString(1, username);
            uUpdateOne.setInt(2, gender);
            uUpdateOne.setInt(3, tidiness);
            uUpdateOne.setInt(4, noise);
            uUpdateOne.setInt(5, sleep);
            uUpdateOne.setInt(6, wake);
            uUpdateOne.setInt(7, pet);
            uUpdateOne.setInt(8, visitor);
            uUpdateOne.setString(9, hobby);

            uUpdateOne.setInt(10, uid);
            uUpdateOne.execute();
            return uid;
        } catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }
    }

    // read detail information of a user
    public DataRow readOne(int id) {
        DataRow res = null;
        try {
            uSelectOne.setInt(1, id);
            ResultSet rs = uSelectOne.executeQuery();
            if (rs.next()) {
                res = new DataRow(rs.getInt("uid"), rs.getString("username"), rs.getString("email"), rs.getInt("gender"), rs.getInt("tidiness"), rs.getInt("noise"), rs.getInt("sleep"), rs.getInt("wake"), rs.getInt("pet"), rs.getInt("visitor"), rs.getString("hobby"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return res;
    }

    // check if a user is Admin or not
    public DataAdmin checkAdmin(int id) {
        DataAdmin res = null;
        try {
            uSelectOne.setInt(1, id);
            ResultSet rs = uCheckAdmin.executeQuery();
            if (rs.next()) {
                res = new DataAdmin(rs.getInt("admin"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return res;
    }

    // delete the user form tbluser
    public boolean deleteOne(int id) {
        try {
            uDeleteOne.setInt(1, id);
            uDeleteOne.execute();
            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    
}